spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;'
    platform: h2
    username: GUEST
    password: abc
    driverClassName: org.h2.Driver
    hikari: >-
      minimumIdle :2 maximumPoolSize:20 idleTimeout:30000 maxLifetime:2000000
      connectionTimeout:30000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  
    